### ISSUE TITLE
Usage Guide

### ISSUE THREAD

**Issue by namangangwar** [kkoooqq/fakebrowser#1]
Hey, If you don't mind can you please provide some instructions on how to use this project?

**Comment by kkoooqq** [comment]
> Hey, If you don't mind can you please provide some instructions on how to use this project?

Thanks.
The code has bypassed many detection programs, but I think it's not perfect yet.

I'm busy writing code to bypass detection, keyboard, emoji, audio, bluetooth, unicode, rtc Capabilities...

After I finish writing these functions, I will make the project into docker, npm and write out the details of how to use it (it's very very easy to use).

Thank you for your patience. I'll @ you when I'm done.

**Comment by namangangwar** [comment]
Alright! I'll be looking forward to using it.

**Comment by kkoooqq** [comment]
Done, please check [readme.md](https://github.com/kkoooqq/fakebrowser/blob/main/README.md).

@namangangwar
