### ISSUE TITLE
some fingerprints not change

### ISSUE THREAD

**Issue by chaojixiaoyao** [kkoooqq/fakebrowser#11]
demo2-diff-fp1.js and demo2-diff-fp2.js method only change WEBGL and CANVAS fingerprint, 
Fonts, Audio and DOMRect does not change.

I use https://abrahamjuliot.github.io/creepjs/ testing

**Comment by kkoooqq** [comment]
Fonts fingerprinting I should have done, Audio / DOMRect fingerprinting is not implemented for now.

TODO: Audio fingerprint

**Comment by chaojixiaoyao** [comment]
> Fonts fingerprinting I should have done, Audio / DOMRect fingerprinting is not implemented for now.
> 
> TODO: Audio fingerprint

again testing
Fonts doesn't work.

**Comment by kkoooqq** [comment]
I'll check again when I get up, I need to sleep now

**Comment by chaojixiaoyao** [comment]
sweet dreams.

**Comment by kkoooqq** [comment]
demo2-diff-fp2.js

<img width="746" alt="image" src="https://user-images.githubusercontent.com/43202488/139681527-11fc54d5-4bb6-447e-b4c6-8fdf11ff7dc9.png">

<img width="776" alt="image" src="https://user-images.githubusercontent.com/43202488/139681561-dff85f03-f647-4796-8a5f-f21224361de9.png">

**Comment by kkoooqq** [comment]
I opened a new issue to record TODO and I closed this one of yours

#16
