### ISSUE TITLE
Stuck when testing CreepJS in headless

### ISSUE THREAD

**Issue by soulkirito** [kkoooqq/fakebrowser#12]
I tested the CreepJS in headless with the remote debugging port opened. It stuck as shown below:
![image](https://user-images.githubusercontent.com/66830063/139639273-ab6b0dba-d4d1-4a8a-99c3-7a9f2393fb9b.png)

**Comment by kkoooqq** [comment]
Hooking SharedWorker is not very stable, I continue to optimize. Thanks for testing.

**Comment by kkoooqq** [comment]
@soulkirito 
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/43202488/139865864-2fe8fdd5-bc53-442e-b43f-de2f0f1c336d.png">

Can you help me to see more details of the exception? I cannot reproduce. For example, expand here and see what the call stack is.
Also, what is your chrome, node, OS version? I'll try to emulate your environment and try.

**Comment by soulkirito** [comment]
@kkoooqq 
![image](https://user-images.githubusercontent.com/66830063/139967491-d9688cbf-e839-477d-9c61-e72f2d32af2e.png)
Chrome > 95.0.4638.69
Node > 14.17.2
OS > Windows 10

**Comment by kkoooqq** [comment]
Thank you so much

**Comment by kkoooqq** [comment]
fix.
