### ISSUE TITLE
chrome args

### ISSUE THREAD

**Issue by Rumatoid** [kkoooqq/fakebrowser#14]
How I can dont to use _kDefaultLaunchArgs_?

**Comment by kkoooqq** [comment]
There is no direct way to remove kDefaultLaunchArgs. I'll think about how to provide this modification.

These parameters are the optimal ones I got after a lot of testing.
Which ones would you like to add or remove?

**Comment by Rumatoid** [comment]
everything because zombie processes began to appear

**Comment by kkoooqq** [comment]
This seems to a bug, I'll fix it now.

**Comment by kkoooqq** [comment]
> everything because zombie processes began to appear

Please update to 0.0.30:

```javascript
// Don't forget to close your browser to release resources
await fakeBrowser.shutdown();
```

**Comment by Rumatoid** [comment]
Yep, now the browser does not freeze and zombies don't appear
Thank you 👍
