### ISSUE TITLE
Unexpected token '||='

### ISSUE THREAD

**Issue by Rumatoid** [kkoooqq/fakebrowser#15]
I got error in _node_modules\fakebrowser\dist\cjs\Driver.js:182_ 
outerWidth ||= innerWidth;

**Comment by kkoooqq** [comment]
I'll check it when I get home in half an hour

**Comment by kkoooqq** [comment]
What exception are you getting? 
Is it possible that your version of node doesn't support the ||= operator?

**Comment by kkoooqq** [comment]
Only node 15 and above support this operator. I'll write it in a different way to improve compatibility.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment

**Comment by Rumatoid** [comment]
Oh, yes, I use 14 version

**Comment by kkoooqq** [comment]
New version updated, you don't need to update your node anymore.
