### ISSUE TITLE
--disable-web-security and permissions

### ISSUE THREAD

**Issue by Rumatoid** [kkoooqq/fakebrowser#19]
I have to dont use --disable-web-security, and I got error 

> VM6039:4 Uncaught DOMException: Blocked a frame with origin

Because of 
```js
const isSecure = 'undefined' == typeof window ? true : window.top.document.location.protocol.startsWith('https');
```
in `src\plugins\evasions\navigator.permissions\index.js`

You can use CDP function to spoof permissions

```js
let permissions = {
    accelerometer: 'granted',
    camera: 'prompt',
    'clipboard-read': 'prompt',
    'clipboard-write': 'granted',
    geolocation: 'prompt',
    'background-sync': 'granted',
    magnetometer: 'granted',
    microphone: 'prompt',
    midi: 'granted',
    notifications: 'prompt',
    'payment-handler': 'granted',
    'persistent-storage': 'prompt',
  };

  for (let permission in permissions) {
    await page._client.send('Browser.setPermission', {
      permission: { name: permission },
      setting: permissions[permission],
    });
  }
```

> PS Sorry for my English

**Comment by kkoooqq** [comment]
Superb! Can you fork and then PR? This project needs to be maintained by everyone. There are so few people doing this across github. Or maybe it's highly secret and no one else wants to share it 😿😿

**Comment by Rumatoid** [comment]
I can try to PR, but I never did it

**Comment by kkoooqq** [comment]
--disable-web-security I haven't looked into yet, I also found problems with this switch turned on in the fingerprint.js pro version. I will keep on this issue.

**Comment by Rumatoid** [comment]
Where I can check permissions in Workers, because I dont know how CDP _Browser.setPermission_ work with workers ?

**Comment by kkoooqq** [comment]
I haven't used Browser.setPermission, I'm not sure, you can try writing a unitest with jest?

**Comment by kkoooqq** [comment]
Browser.setPermission is so awesome, I checked the documentation and I can remove the evasion - navigator.permissions ?

**Comment by Rumatoid** [comment]
yes, but I never wrote jest tests, but I use Browser.setPermission with check it in [https://abrahamjuliot.github.io/creepjs/](url)
And never worked with workers, and now I checked that, without _--disable-web-security_ getting Error 
```
DOMException: Failed to construct 'SharedWorker': Script at 'http://127.0.0.1:6170/patchWorker?type=sharedWorker&uuid=9a8786f7444d135bcfd6a061d06525be&relUrl=about%3Ablank&workerUrl=https%3A%2F%2Fabrahamjuliot.github.io%2Fcreepjs%2Ftests%2Fworkers.js' cannot be accessed from origin 'https://abrahamjuliot.github.io'.
    at https://abrahamjuliot.github.io/creepjs/tests/workers.js:481:26
    at new Promise (<anonymous>)
    at getSharedWorker (https://abrahamjuliot.github.io/creepjs/tests/workers.js:468:10)
    at https://abrahamjuliot.github.io/creepjs/tests/workers.js:592:3
    at https://abrahamjuliot.github.io/creepjs/tests/workers.js:733:3
```
![image](https://user-images.githubusercontent.com/52918376/139926690-986a7eee-ab5c-4ca1-a340-3836dd773d62.png)

**Comment by kkoooqq** [comment]
Yes, if I remove the --disable-web-security, then my local 127.0.0.1 js script is not accessible across the domain.

**Comment by kkoooqq** [comment]
You can remove the evasion worker to test it, in pptrpatch.js

**Comment by Rumatoid** [comment]
Hmmm, without workers patch, got problem only with Shared 
![image](https://user-images.githubusercontent.com/52918376/139930017-d1447e02-8af7-41d4-b21a-d2a88b6f209b.png)

**Comment by kkoooqq** [comment]
Yes, sharedworker's patch I now use in a very nasty way, and even have to create an http service!!!

I'm working on how to optimize.

So is there a conclusion yet, does Browser.setPermission work?

**Comment by Rumatoid** [comment]
Yes, I'm using it for few months

**Comment by kkoooqq** [comment]
Great! fork & PR ? 🐣🐣🐣

**Comment by Rumatoid** [comment]
I'll try to do it

**Comment by kkoooqq** [comment]
Thanks a lot! I'll move on to other fingerprint processing. Too many things to do. #16

**Comment by Rumatoid** [comment]
Sorry, can I talk to you in some chat?

**Comment by kkoooqq** [comment]
I merged your commit. Do you think you need to collect different permissions for each user in dumpdd.js? What does this depend on? Different OS? Different chrome versions?

**Comment by kkoooqq** [comment]
WhatsApp +1 971 801 8130

**Comment by Rumatoid** [comment]
> I merged your commit. Do you think you need to collect different permissions for each user in dumpdd.js? What does this depend on? Different OS? Different chrome versions?

Yes, because on mobile - nfc is prompt not unknown

**Comment by kkoooqq** [comment]
#24
