### ISSUE TITLE
Cannot login gmail

### ISSUE THREAD

**Issue by workingxx92** [kkoooqq/fakebrowser#21]
Couldn’t sign you in
This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can try again to sign in.

**Comment by kkoooqq** [comment]
Website?

**Comment by workingxx92** [comment]
<img width="1007" alt="Screen Shot 2021-11-03 at 7 34 38 PM" src="https://user-images.githubusercontent.com/86577210/140060926-0e4c665f-1a11-412d-a6d8-d97ef846b885.png">

**Comment by kkoooqq** [comment]
<img width="621" alt="image" src="https://user-images.githubusercontent.com/43202488/140062921-e39ffb11-7988-43ae-b24d-c62890ff21f6.png">


https://github.com/kkoooqq/fakebrowser/blob/main/demo/demo3-fake-user-action.js
