### ISSUE TITLE
The new 'evasions/webgl' code doesnt work with ServiceWorker

### ISSUE THREAD

**Issue by gaosong886** [kkoooqq/fakebrowser#26]
![1636909168(1)](https://user-images.githubusercontent.com/14159932/141690670-efdff96b-95fe-462a-89c4-846909edec40.png)

webgl params is undefined.

BTW, I think you forgot to remove 'content-length'  from the response headers which send by 'InternalHTTPServer'.

**Comment by kkoooqq** [comment]
thank you so much, please update to 0.0.55
