### ISSUE TITLE
Headless mode click,drag,press uaction not work?

### ISSUE THREAD

**Issue by huozhenlin** [kkoooqq/fakebrowser#28]
When I use fakebrowser in headless mode, I can not use screenshot api, also, mouse.click,mouse.move,mouse.up api are not work too。 What should i do when I meet slider verification code
![image](https://user-images.githubusercontent.com/19356940/142023898-7f51a837-bbc0-40b0-8466-f0a621057845.jpeg)

**Comment by kkoooqq** [comment]
thanks for the feedback, I'll update the code tonight

**Comment by kkoooqq** [comment]
Please send me your wechat number so I can contact you directly for more information
kkoooqq@protonmail.com

**Comment by huozhenlin** [comment]
> Please send me your wechat number so I can contact you directly for more information
> 
> kkoooqq@protonmail.com

i had send you an email,please check

**Comment by kkoooqq** [comment]
This bug has been merged into #16: because mouse.move runs very slowly under windows
