### ISSUE TITLE
Get Crash when going to some websites

### ISSUE THREAD

**Issue by workingxx92** [kkoooqq/fakebrowser#29]
![Screen Shot 2021-11-18 at 7 15 33 AM](https://user-images.githubusercontent.com/86577210/142304249-f57f7d43-0b87-4622-a30d-89b9896953fb.png)
![Screen Shot 2021-11-18 at 7 16 02 AM](https://user-images.githubusercontent.com/86577210/142304329-6f5a52f5-d715-41cd-8069-4af79955944d.png)
![Screen Shot 2021-11-18 at 7 16 28 AM](https://user-images.githubusercontent.com/86577210/142304378-b991e69c-8b40-453f-82e9-8b35aa46d6d3.png)
![Screen_Shot_2021-11-16_at_8 55 22_PM_1](https://user-images.githubusercontent.com/86577210/142304397-8497a3e5-cf14-43ab-9978-09f5f1cbb01a.png)
![Screen_Shot_2021-11-15_at_11 33 14_AM](https://user-images.githubusercontent.com/86577210/142305657-963044f3-3dbc-40b7-b69f-a696b1c53dc2.png)

**Comment by kkoooqq** [comment]
thank you very much, I will fix it as soon as possible

**Comment by kkoooqq** [comment]
stackoverflow & googlemerchant fixed, pinterest also partially fixed, the rest is worker issue, already in #16  there is this problem
