### ISSUE TITLE
regenerate device-hub json files

### ISSUE THREAD

**Issue by analtevs** [kkoooqq/fakebrowser#3]
noticed the current device profiles are out of sync with the current [DeviceDescriptor](https://github.com/kkoooqq/fakebrowser/blob/main/src/DeviceDescriptor.ts) and [dumpDD](https://github.com/kkoooqq/fakebrowser/blob/main/src/dumpDD.js);

possible to regenerate those files?

**Comment by kkoooqq** [comment]
> noticed the current device profiles are out of sync with the current [DeviceDescriptor](https://github.com/kkoooqq/fakebrowser/blob/main/src/DeviceDescriptor.ts) and [dumpDD](https://github.com/kkoooqq/fakebrowser/blob/main/src/dumpDD.js);
> 
> possible to regenerate those files?

Thank you for submitting the update.
I will update dumpDD tomorrow:

* Collection user's keyboard layout used to complete the keyboard fingerprint.
* window's OwnPropertyNames to complete Window Features fingerprint.
* document.documentElement keys to complete HTMLElementVersion.

Above will have subtle differences in different computers and operating systems, so I have to simulate these.

**Comment by analtevs** [comment]
I'll get mine updated and submit a few more once I return from vacation.
