### ISSUE TITLE
userAction.simClickElement not work in headless mode

### ISSUE THREAD

**Issue by pkjy** [kkoooqq/fakebrowser#32]
I use userAction.simClickElement and it's very smooth in my code with headless false.
but when I change headless to true , the program will be blocked in userAction.simClickElement line .

e.g.

``` javascript
console.log('start')
const loginPass = await page.$('#npwd');
await userAction.simClickElement(loginPass); // will be blocked in here 
console.log('end') // never tick with  headless:true
```

userAction封装的方法，在headless为true情况下，会一直卡着？

**Comment by kkoooqq** [comment]
之前discord群里有人遇到这个问题，好像是因为node版本不正确。你的操作系统/node版本是什么？

**Comment by pkjy** [comment]
> 之前discord群里有人遇到这个问题，好像是因为node版本不正确。你的操作系统/node版本是什么？

windows10 / nodejs v14.15.0

**Comment by pkjy** [comment]
> 之前discord群里有人遇到这个问题，好像是因为node版本不正确。你的操作系统/node版本是什么？

哪些node版本是确定没问题的？我可以去试下。

**Comment by kkoooqq** [comment]
我在macos, win10, centos 7, ubuntu 18, node16.13.0都测试过OK

**Comment by pkjy** [comment]
> 我在macos, win10, centos 7, ubuntu 18, node16.13.0都测试过OK

好，我试试 node 16.13.0

**Comment by pkjy** [comment]
破案了， `await page.mouse.move()` 时间阻塞在这个方法上，这个应该是pptr提供的原生api吧。我尝试把options删掉，也没用，时间还是花在这这里。后面的sleep那没啥问题。
![image](https://user-images.githubusercontent.com/14119424/146389171-de75d5b1-a109-4c42-8394-039f1e42ae89.png)

**Comment by kkoooqq** [comment]
你跟一下代码看看 page.setViewport怎么设置的

**Comment by pkjy** [comment]
> 你跟一下代码看看 page.setViewport怎么设置的
headless:true
当前setViewport参数 {
  width: 969,
  height: 901,
  isMobile: false,
  hasTouch: false,
  deviceScaleFactor: 1
}
headless:false
当前setViewport参数 {
  width: 969,
  height: 901,
  isMobile: false,
  hasTouch: false,
  deviceScaleFactor: 1
}
![image](https://user-images.githubusercontent.com/14119424/146702610-86c104c0-cd99-4a73-a736-c3c4301d7a3f.png)
没看出来有什么区别

**Comment by pkjy** [comment]
> 我在macos, win10, centos 7, ubuntu 18, node16.13.0都测试过OK

chrome版本呢? 我chrome是 96.0.4664.11

**Comment by pkjy** [comment]
找到问题了，这个启动参数导致的。注释了这个`'--deterministic-mode'`启动参数后，无头下的行为也很正常了。

![image](https://user-images.githubusercontent.com/14119424/146705776-3985f22a-6fb4-479d-9d9b-68525f30393d.png)

**Comment by kkoooqq** [comment]
谢谢啊，我更新一下
