### ISSUE TITLE
iphey test

### ISSUE THREAD

**Issue by yt20aqin** [kkoooqq/fakebrowser#38]
Hi, I can't bypass this test too 
![image](https://user-images.githubusercontent.com/33801827/147768065-ade9787d-f604-4a1c-a219-c0f8caf95279.png)
https://iphey.com/#hardware-text

**Comment by kkoooqq** [comment]
fakebrowser with fakechrome could bypass the test, could find me in Discord for details on how to do this.

**Comment by ejames17** [comment]
Trying matching the OS
