### ISSUE TITLE
Inject js not working

### ISSUE THREAD

**Issue by Jiw0cha** [kkoooqq/fakebrowser#45]
Hi.

Inject js not working, if use mouse(hardware/not use automation with puppeteer) click to link.

step to reproduce:

open https://abrahamjuliot.github.io/creepjs/ over FakeBrowser  

scroll down page and click mouse (example Screen).

**Comment by kkoooqq** [comment]
https://user-images.githubusercontent.com/43202488/149577764-bdb612e2-139d-4abc-9438-5e1b7d466cfc.mov

works well in my side. Emulating windows with a mac

**Comment by Jiw0cha** [comment]
Click open new Tab.

**Comment by kkoooqq** [comment]
> 

it's issue of puppeteer, 

https://github.com/puppeteer/puppeteer/issues/3667
You could use CDP to make some hooks of your own

ref:
https://github.com/microsoft/playwright/issues/1101
https://github.com/berstend/puppeteer-extra/issues/23

feel free to PR.
