### ISSUE TITLE
dumpDD Android.json problem

### ISSUE THREAD

**Issue by ong379** [kkoooqq/fakebrowser#46]
Hi, I have a problem running using android.json.

I've tried dumpDD to 4 different real androids, but the dumpDD script results are always problematic.
I've tried dumpDD to windows, the results can run smoothly, but specifically for android there can't be run.
Please fix this problem for android.json. Thank You

![image](https://user-images.githubusercontent.com/44989447/150077884-d2c7b143-63e7-4175-83ed-b088dc05836d.png)
![image](https://user-images.githubusercontent.com/44989447/150077928-0424a61e-f47a-42b0-b528-0142bb336614.png)
![image](https://user-images.githubusercontent.com/44989447/150077980-6d15875d-0153-4687-989a-9e9ccfb8cbb4.png)
![image](https://user-images.githubusercontent.com/44989447/150078105-d9dac77c-9b36-40f5-be4c-9920ef842a92.png)

**Comment by orhancekic** [comment]
issue is there is a SpeechSynthesis member of window object but zero length. This logic wasnt expected on dumpDD.js. this problem generally exist on linux based machines

**Comment by kkoooqq** [comment]
fixed
