### ISSUE TITLE
Quickstart Guide

### ISSUE THREAD

**Issue by namangangwar** [kkoooqq/fakebrowser#6]
Hey, can someone provide a quick start guide for this project?
So far I've compiled the code
`npm run build`
Then copied the lib folder into my project. After that, I'm trying to start FakeBrowser:

    import { FakeBrowserBuilder } from "./lib/fakebrowser/FakeBrowser";
    (async () => {
    	const fakeBrowser = new FakeBrowserBuilder();
    	const browser = await fakeBrowser.launch();
    })();

 but it's giving me an error:
 

    [INFO] 01:41:16 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.4.4)
	(node:7344) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: undefined == true  
    at FakeBrowserBuilder.<anonymous> (D:\Projects\test\src\lib\fakebrowser\FakeBrowser.js:35:29)
    at step (D:\Projects\test\src\lib\fakebrowser\FakeBrowser.js:33:23)
    at Object.next (D:\Projects\test\src\lib\fakebrowser\FakeBrowser.js:14:53)
    at D:\Projects\test\src\lib\fakebrowser\FakeBrowser.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Projects\test\src\lib\fakebrowser\FakeBrowser.js:4:12)
    at FakeBrowserBuilder.launch (D:\Projects\test\src\lib\fakebrowser\FakeBrowser.js:70:16)     
    at D:\Projects\test\src\main.ts:5:36
    at step (D:\Projects\test\src\main.ts:33:23)
    at Object.next (D:\Projects\test\src\main.ts:14:53)
	(Use `node --trace-warnings ...` to show where the warning was created)
	(node:7344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise 
	which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
	(node:7344) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero 
	exit code.

**Comment by kkoooqq** [comment]
> Hey, can someone provide a quick start guide for this project? So far I've compiled the code `npm run build` Then copied the lib folder into my project. After that, I'm trying to start FakeBrowser:
> 
> ```
> import { FakeBrowserBuilder } from "./lib/fakebrowser/FakeBrowser";
> (async () => {
> 	const fakeBrowser = new FakeBrowserBuilder();
> 	const browser = await fakeBrowser.launch();
> })();
> ```
> 
> but it's giving me an error:
> 
> ```
> [INFO] 01:41:16 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.4.4)
> (node:7344) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: undefined == true  
> at FakeBrowserBuilder.<anonymous> (D:\Projects\test\src\lib\fakebrowser\FakeBrowser.js:35:29)
> at step (D:\Projects\test\src\lib\fakebrowser\FakeBrowser.js:33:23)
> at Object.next (D:\Projects\test\src\lib\fakebrowser\FakeBrowser.js:14:53)
> at D:\Projects\test\src\lib\fakebrowser\FakeBrowser.js:8:71
> at new Promise (<anonymous>)
> at __awaiter (D:\Projects\test\src\lib\fakebrowser\FakeBrowser.js:4:12)
> at FakeBrowserBuilder.launch (D:\Projects\test\src\lib\fakebrowser\FakeBrowser.js:70:16)     
> at D:\Projects\test\src\main.ts:5:36
> at step (D:\Projects\test\src\main.ts:33:23)
> at Object.next (D:\Projects\test\src\main.ts:14:53)
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:7344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise 
> which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> (node:7344) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero 
> exit code.
> ```

Done, please check [readme.md](https://github.com/kkoooqq/fakebrowser/blob/main/README.md).
