### ISSUE TITLE
Did you have plan to support automation in fakebrowser

### ISSUE THREAD

**Issue by workingxx92** [kkoooqq/fakebrowser#7]

**Comment by kkoooqq** [comment]
FakeBrowser is based on puppeteer and can certainly do automated things. Do you have any better suggestions?

**Comment by workingxx92** [comment]
Pls support proxy

**Comment by kkoooqq** [comment]
> Pls support proxy and create profile data

https://github.com/kkoooqq/fakebrowser/blob/main/demo/demo4-proxy.js
