### ISSUE TITLE
fingerprint always the same

### ISSUE THREAD

**Issue by chaojixiaoyao** [kkoooqq/fakebrowser#9]
Great job!
fakebrowser like a true browser.

fakebrowser always the same fingerprint.
I saw plugins path has fingerprint file. how do fakebrowser use it? which method use 

thanks a lot

**Comment by kkoooqq** [comment]
我会在新的demo里写清楚。写好以后@你。

**Comment by chaojixiaoyao** [comment]
> 我会在新的demo里写清楚。写好以后@你。

太好了！顺便讲讲UserAgentHelper.ts如何用，这应该是随机useragent吧

**Comment by kkoooqq** [comment]
这只是一个工具类，用来分析ua的内容。不包含生成ua。
不要自己生成ua放到fakeBrowser里使用，指纹会脏（ua与别的浏览器参数对应不上）。

**Comment by chaojixiaoyao** [comment]
> 这只是一个工具类，用来分析ua的内容。不包含生成ua。 不要自己生成ua放到fakeBrowser里使用，指纹会脏（ua与别的浏览器参数对应不上）。

**Comment by kkoooqq** [comment]
@chaojixiaoyao 请更新至0.0.20版然后看首页说明

**Comment by chaojixiaoyao** [comment]
> @chaojixiaoyao 请更新至0.0.20版然后看首页说明
